#!/usr/bin/env bash

ARCH=$(uname -m | sed 's/aarch64/arm64/g' | sed 's/x86_64/amd64/g')

mkdir -p /var/lib/docker-plugins/rclone/config
mkdir -p /var/lib/docker-plugins/rclone/cache

# docker commands require socket to be active
while [ ! -S /var/run/docker.sock ]; do
  sleep 1
done

docker plugin rm rclone
docker plugin install rclone/docker-volume-rclone:${ARCH} args="-v" --alias rclone --grant-all-permissions
